name: Clean Old Files

on:
  workflow_dispatch:

  workflow_call:
    
jobs:
  clean:
    runs-on: ubuntu-latest
      
    steps:

    - name: Remove the Old Kista Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Kista'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"

    - name: Remove the Old Kista.DynamicLinq Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Kista.DynamicLinq'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"

    - name: Remove the Old Kista.InMemory Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Kista.InMemory'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"

    - name: Remove the Old Kista.MongoFramework Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Kista.MongoFramework'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"

    - name: Remove the Old Kista.MongoFramework.MultiTenant Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Kista.MongoFramework.MultiTenant'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"

    - name: Remove the Old Kista.EntityFramework Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Kista.EntityFramework'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"


    - name: Remove the Old Kista.Manager Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Kista.Manager'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"

    - name: Remove the Old Kista.Manager.AspNetCore Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Kista.Manager.AspNetCore'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"

    - name: Remove the Old Kista.Manager.DynamicLinq Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Kista.Manager.DynamicLinq'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"

    - name: Remove the Old Kista.Manager.EasyCaching Package
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'Kista.Manager.EasyCaching'
        package-type: 'nuget'
        min-versions-to-keep: 10
        delete-only-pre-release-versions: "true"